### ISSUE TITLE
Exclude AJAX from the cache (for WooCommerce needs)

### ISSUE THREAD

**Issue by rhvs** [nicolargo/varnish-nginx-wordpress#13]
Hi! I'm struggling to exclude AJAX from the cache, so WooCommerce will work. Any idea how to do this?

**Comment by bahadoribnm** [comment]
when add in plus bottom for add more than 1 of product to shopping cart in wordpress, I see this error:

Request URL: https://dcashop.com/cart/
Request Method: POST
Status Code: 503 Backend fetch failed
x-requested-with: XMLHttpRequest

 in my vcl I add this value but not work:

 ```
# The code below makes sure the AJAX "add to cart" function works
    set req.url = regsub(req.url, "add-to-cart=\d+_\d+&", "");

  # Do not cache AJAX requests.
    if (req.http.X-Requested-With == "XMLHttpRequest") {
        return(pass);
    }

  # Post requests will not be cached
    if (req.http.Authorization || req.method == "POST") {
        return (pass);
    }
```
